name: RL Scan with rl-scanner-cloud-only action - Trial instance

on:
  workflow_dispatch:

jobs:
  Build-And-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set previous run number
        run: |
          echo "PREV_RUN_NUMBER=$(($GITHUB_RUN_NUMBER-1))" >> ${GITHUB_ENV}
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Build
        run: |
          mvn -B clean package

      - name: RL scan
        continue-on-error: true
        id: rl-scan

        env:
          RLPORTAL_ACCESS_TOKEN: ${{ secrets.RL_API_TOK }}

        uses: reversinglabs/gh-action-rl-scanner-cloud-only@v1
        with:
          rl-verbose: true
          rl-portal-server: trial
          rl-portal-org: Trial
          rl-portal-group: 'ProdMgmt'
          rl-timeout: 5
          rl-submit-only: false
          artifact-to-scan: 'target/struts2-showcase.war'
          rl-package-url: Apache/Struts2showcaseGHA@v2.5.28-${{ github.run_number }}
          rl-diff-with: v2.5.28-${{ env.PREV_RUN_NUMBER }}

      - name: Output scan status
        if: success() || failure()
        run: |
          echo "The status is: '${{ steps.rl-scan.outputs.status }}'"
          echo "The description is: '${{ steps.rl-scan.outputs.description }}'"
